// Scrape codepens: https://codepen.io/your-work/?grid_type=list&cursor=ZD0xJm89MCZwPTEmdj01MDEwMzU0Ng==
// last scraped: 9/20/2021
// [...document.querySelectorAll(".title")].map((el) => {
//   const title = el.title;
//   const link = el.querySelector("a");
//   const id = link.href.split("/").slice(-1)[0];
//   return { title, id };
// });

export default [
  { name: "Analog Clock", id: "MWwZBgP", show: true },
  { name: "Bada-Boom", id: "RKOexP" },
  {
    name: "Ball bouncing canvas",
    id: "PJLVMp",
    show: true,
  },
  { name: "Ball move", id: "dxGMRw" },
  {
    name: "Baseball Standings",
    id: "rNaKaqK",
  },
  { name: "Block loaders", id: "qpPeLQ" },
  { name: "Blogger 5000", id: "LWrENq", show: true },
  { name: "calculate", id: "ewKxVg", show: true },
  { name: "Card Board", id: "rodLgL" },
  { name: "Carousel", id: "RwWpWMj" },
  { name: "Cat carousel", id: "ZEQoXZb" },
  { name: "Centering nav", id: "bYXOpO" },
  {
    name: "Change colors on scroll",
    id: "jObWvme",
    show: true,
  },

  { name: "cities", id: "omRKgy" },
  { name: "Clocks!", id: "zjVZOM", show: true },
  { name: "Coin toss", id: "LwRVPb" },
  { name: "Color compare", id: "mgvqyL", show: true },
  { name: "Connect 4!", id: "bGdrOxq", show: true },
  { name: "Create form", id: "NBbwGR" },
  {
    name: "CSS Digital Hex Clock",
    id: "VpdYjO",
  },
  { name: "CSS is Awesome", id: "jOPBoNR", show: true },
  {
    name: "CSS Social Card Hover Effect",
    id: "YzKdjbV",
  },
  { name: "d3 stuff", id: "wEvywB" },
  { name: "date ranges", id: "QWyWXxE" },
  { name: "Dice game", id: "abvWYEo" },
  { name: "Drop7", id: "zYGRWMO", show: true },
  { name: "Ellipse animate", id: "MaWmbo" },
  { name: "Etch a sketch", id: "QWjOEGy" },
  { name: "Faded border", id: "ybOjNb" },
  { name: "Fast ToDo", id: "zmVNZY" },
  {
    name: "FCC: Tribute Page",
    id: "JEVadJ",
  },
  { name: "Flatty Shapes", id: "xXmXrK" },
  {
    name: "Flexbox education",
    id: "rmmwgo",
  },
  { name: "Forrest!", id: "mxrooE", show: true },
  {
    name: "Four Word Phrase Generator",
    id: "eRVOwZ",
    show: true,
  },
  { name: "guitar fret", id: "gVxvYE" },
  { name: "Hover to Spin", id: "WgpXoX" },
  {
    name: "Line up with Flex",
    id: "WBLxYJ",
  },
  { name: "List layout", id: "eYmjEZB" },
  { name: "Loading border", id: "eweEPK" },
  { name: "Memory game", id: "KKdpyer", show: true },
  { name: "Menu thing", id: "gOYLwbX" },
  { name: "New Loader", id: "xegmRY", show: true },
  { name: "NWWYjLa", id: "NWWYjLa" },
  {
    name: "Overflow example",
    id: "XWrQgpV",
  },
  { name: "pEkkOr", id: "pEkkOr" },
  { name: "Pick a dog!", id: "rNVZMbP" },
  {
    name: "Random Number plot",
    id: "gOpGmwV",
  },
  {
    name: "React Leaderboard",
    id: "MWKWyVa",
    show: true,
  },
  {
    name: "Redundant Robot Cube",
    id: "qRRXLL",
  },
  { name: "Robot Head", id: "oLpQXW", show: true },
  { name: "Rocket!", id: "yMoqbr" },
  { name: "rotate circle", id: "LOPmEv" },
  { name: "Row layout", id: "QaeyXm" },
  {
    name: "Simply image upload",
    id: "PoqNadJ",
  },
  {
    name: "Spell it out for me",
    id: "RwrLrNM",
    show: true,
  },
  {
    name: "square switchy thingy",
    id: "xgBozg",
  },
  { name: "Stars", id: "NjVLLO", show: true },
  { name: "Stopwatch", id: "KrGBdJ", show: true },
  {
    name: "Temperature converter",
    id: "bygWeO",
    show: true,
  },
  { name: "Text Mask", id: "arYrMw" },
  { name: "The Moon", id: "zwXjaB", show: true },
  { name: "The Sun", id: "BRbZQd", show: true },
  { name: "Top Secret info", id: "JjjvGVL" },
  { name: "Tripshit", id: "GPBEPr" },
  { name: "URL qs", id: "PoPJxpo" },
  {
    name: "Visualize Longest Palindromic Sequence",
    id: "pogvweg",
  },
  { name: "vpoLdE", id: "vpoLdE" },
  { name: "Walking Man", id: "XWrNyKB", show: true },
  { name: "Words disappear", id: "PeQVXz", show: true },
  { name: "WqomvM", id: "WqomvM", show: true },
  { name: "parse RGB", id: "KKqadRW" },
  { name: "AnimationEnd", id: "poPmeaJ" },
  { name: "Fetch RSS", id: "MWmqzYm" },
  { name: "d3_barchart_02_title", id: "ExmYqbQ" },
  { name: "d3_barchart_01_initial", id: "QWvLXrR" },
  { name: "D3 Bar Chart", id: "YzZeJXO" },
  { name: "Chutes and Ladders", id: "abJJLWJ" },
  { name: "textarea replace", id: "GRWZrOG" },
  { name: "React Links", id: "eYvpXyg" },
  { name: "React ToDo", id: "dyvYYjQ" },
  { name: "Mock site", id: "LYWEMgZ" },
  { name: "Mock site", id: "ExWadRm" },
  { name: "canvas thumbs", id: "xxgoaaY" },
  { name: "wvgbQeE", id: "wvgbQeE" },
  { name: "Demo", id: "KKaNEgd" },
  { name: "svg lines", id: "abpmBbZ" },
  { name: "War!", id: "bGgexEa" },
  { name: "Brief layout", id: "xxRoERG" },
  { name: "Mouse Odometer", id: "RwoYQYY" },
  { name: "example layout", id: "dyOpMQO" },
  { name: "GRNqGdM", id: "GRNqGdM" },
  { name: "layout", id: "LYbGKEd" },
  { name: "Drop Cats", id: "wvoKYJO" },
  { name: "Spinning Cube No Robot", id: "GRNpdax" },
  { name: "table load", id: "yLVyNQp" },
  { name: "Link URLs OOJS", id: "gOLYNLG" },
  { name: "Simple grid", id: "BaLVLEm" },
  { name: "Calendar Picker", id: "dypJPzZ" },
  { name: "calculator", id: "ExgwZYY" },
  { name: "canvas grid", id: "ExgXMEW" },
  { name: "SVG gradient animation loop", id: "poEPwOR" },
  { name: "SVG Loader With Spinning Gradient", id: "VwKpoEa" },
  { name: "Timers", id: "RwGbpjL" },
  { name: "Shadows", id: "bGeJoJM" },
  { name: "Dot grid", id: "bGeMrxp" },
  { name: "rotate background", id: "vYKjJRM" },
  { name: "Simple Carousel Procedural", id: "Bazxyxj" },
  { name: "Simple Carousel OOP", id: "oNLqrpG" },
  { name: "Flexbox scroll", id: "oNLYZmg" },
  { name: "Happy Cake day!", id: "abZdPaB" },
  { name: "Quiz Game", id: "gOMpKqL" },
  { name: "easy month", id: "WNwEEyd" },
  { name: "Clicker evolution", id: "LYNyqyz" },
  { name: "Mousover image", id: "ZEWWjop" },
  { name: "Bowling", id: "yLOeOMd" },
  { name: "Loading example", id: "ZEWGEJo" },
];
